name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'   # workflow jalan hanya kalau ada tag versi baru

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Verify version consistency
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "v$PKG_VERSION" ]; then
            echo "❌ Tag version ($TAG_VERSION) does not match package.json version (v$PKG_VERSION)"
            exit 1
          fi
          echo "✅ Version check passed: $TAG_VERSION"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
